src/Entity/Advertissement.php
<?php

namespace App\Entity;

use App\Repository\AdvertissementRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdvertissementRepository::class)]
class Advertissement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $job = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $job_desc = null;

    #[ORM\Column(length: 20)]
    private ?string $date = null;

    #[ORM\ManyToMany(targetEntity: 'User', mappedBy: 'id_ad')]
    private Collection $users;

    #[ORM\ManyToOne(inversedBy: 'myAds')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getJobDesc(): ?string
    {
        return $this->job_desc;
    }

    public function setJobDesc(string $job_desc): self
    {
        $this->job_desc = $job_desc;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getIdU(): ?User
    {
        return $this->id_u;
    }

    /**
     * @param User|null $id_u
     */
    public function setIdU(?User $id_u): void
    {
        $this->id_u = $id_u;
    }

    /**
     * @return User|null
     */
    public function getIdOwner(): ?User
    {
        return $this->id_owner;
    }

    /**
     * @param User|null $id_owner
     */
    public function setIdOwner(?User $id_owner): void
    {
        $this->id_owner = $id_owner;
    }

//    /**
//     * @return string
//     */
//    public function getRelease()
//    {
//        return $this->release;
//    }
//
//    /**
//     * @param string $release
//     */
//    public function setRelease($release): void
//    {
//        $this->release = $release;
//    }

}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% set count = 0 %}
{% block body %}
    <div class="container mt-5 mb-3">
        {% if is_granted('ROLE_COMPAGNIE') %}
            <button class="btn btn-outline-secondary mb-3"><a class="text-secondary" href="/nouvelleOffre">Créer une nouvel annonce</a></button>
        {% endif %}
        <div class="row">

            {% for ad in adv %}
                {% block javascripts %}
                <script>
                    $(document).ready(function () {
                        $('#{{ count }}').on("click", function (){
                            document.getElementById("div{{ count }}").innerHTML = document.getElementById("{{ count }}").value;
                            $("#{{ count }}").hide();
                            $("#enregistrer{{ count }}").show();
                        });
                    });
                </script>
                <script>
                    $(document).ready(function (){
                        $("#enregistrer{{ count }}").on("click", function (){
                            let idAd = {{ ad.id }};
                            $.ajax({
                                url: '/enregistrerOffre',
                                type: 'POST',
                                data: {id : idAd},
                                success: function (response) {
                                    console.log(response.success)
                                    console.log()
                                },
                                error: function (response){
                                    alert('Vous êtes surement déconnécté');
                                }
                            });
                        });
                    })
                </script>
                {% endblock %}
                <div class="col-md-4">
                    <div class="card p-3 mb-2">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                                <div class="ms-2 c-details">
                                    <h6 class="mb-0">{{ ad.idOwner.name }}</h6> <span>{{ ad.date }}</span>
                                </div>
                            </div>
                            <div class="badge"> <span>Job</span> </div>
                        </div>
                        <div class="mt-5">
                            <h3 class="heading">{{ ad.job }}</h3>
                            <div id="div{{ count }}"></div>
                            <div class="mt-5">
                                <button class="btn btn-dark" id="{{ count }}" value="{{ ad.jobDesc }}">Voir l'annonce</button>
                                <button class="btn btn-dark" id="enregistrer{{ count }}" value="{{ ad.id }}" style="display: none">Enregistrer l'annonce</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% set count = count + 1 %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index/newAdvForm.html.twig
{% extends '/base.html.twig' %}

{% block body %}
    {% if is_granted('ROLE_COMPAGNIE') %}
        <div class="container py-4 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <h2 class="fw-bold mb-2 text-uppercase">Nouvelle Offre</h2>
                            {{ form(newAdvForm) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container py-4 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <h2 class="fw-bold mb-2 text-uppercase">Vous n'avez pas accès a cette page :-(</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}